name: PR_unit_tests

on:
  pull_request:
    branches:
    - 'master'

jobs:
  unit_test:
    name: Run unit tests on PR in main
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with: { java-version: 1.8 }
      - name: Run unit tests
        run: ./gradlew test
